// Code generated by goctl. DO NOT EDIT.
package Typeslogin

type LoginRequest struct {
	Accout  string `json:"account"`
	Pwd     string `json:"pwd"`
	Imgcode string `json:"imgcode"`
}

type SystemMenus struct {
	Id         int    `json:"id"`
	MenuName   string `json:"menu_name"`
	Icon       string `json:"icon"`
	Pid        int    `json:"pid"`
	sort       int    `json:"sort"`
	MenuPath   string `json:"menu_path"`
	IsShow     int    `json:"is_show"`
	Header     string `json:"header"`
	IsHeader   int    `json:"is_header"`
	IsShowPath int    `json:"is_show_path"`
}

type menus struct {
	path      string
	title     string
	icon      string
	is_header int
	children  []menus
}
type SystemAdmin struct {
	Account string `json:"account"`
	HeadPic string `json:"head_pic"`
	Id      int    `json:"id"`
}
type LoginResponse struct {
	Token             string      `json:"token"`
	Expires_time      int64       `json:"expires_time"`
	Menus             menus       `json:"menus"`
	Logo              string      `json:"logo"`
	LogoSquare        string      `json:"logo_square"`
	NewOrderAudisLink string      `json:"newOrderAudioLink"`
	UniqueAuth        []string    `json:"unique_auth"`
	UserInfo          SystemAdmin `json:"user_info"`
	Version           string      `json:"version"`
}
